version: '3.8'

services:
  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_humble_container
    volumes:
      - ./ros2_ws:/root/ros2_ws
      - ./maps:/root/maps
      - ./config:/root/config
      - ./python:/root/python
      - $HOME/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/serial/by-path:/dev/serial/by-path
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    devices:
      - /dev:/dev
    command: tail -f /dev/null